---
name: PlayerScale
version: 0.0.1
main: YTBJero\PlayerScale\Main
author: YTBJero
api:
- 4.0.0

commands:
  scale:
    description: "PlayerScale command"
    permission: playerscale.command 

permissions:
  playerscale.command:
    default: op
...
